image: maven:3.9.16-openjdk-26
default:
  tags:
    - shellProject
stages:
  - test
Integration test with allure:
  stage: test
  script:
    - mvn clean test
    - mvn allure:report
  artifacts:
    paths:
      - target/allure-results/*