services:
  jenkins:
    image: jenkins/jenkins:lts-jdk21
    container_name: jenkins-ci
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      # Проброс сокета оставляем, чтобы Jenkins слал команды вашему Docker Desktop
      - /var/run/docker.sock:/var/run/docker.sock
    user: root # Нужно только для беспрепятственного чтения docker.sock

volumes:
  jenkins_home: